name:                satSolver
version:             0.1.0.0
github:              "jacobjedwards/satSolver"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jacobjedwards/satSolver#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- unordered-containers
- hashable
- template-haskell
- vector
- text
- bytestring
- haskeline
- mtl
- QuickCheck
- parallel
- tasty
- tasty-hunit
- tasty-quickcheck
- criterion
- Parser
- Stack
- prettyprinter

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wmissing-import-lists
- -Wredundant-constraints
- -Wnoncanonical-monad-instances

library:
  source-dirs: src

executables:
  satSolver-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - satSolver
    - haskeline
    - Parser

tests:
  satSolver-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - satSolver
    - QuickCheck
    - tasty
    - tasty-hunit
    - tasty-quickcheck

benchmarks:
  satSolver-bench:
    main:                Bench.hs
    source-dirs:         bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - satSolver
    - criterion